// This file is part of the Unicode Character Database
// For documentation, see http://www.unicode.org/reports/tr44/
//
// Based on the source file: https://unicode.org/Public/17.0.0/ucd/Jamo.txt
//
// zig fmt: off

pub const Jamo = struct {
    code: u21,
    short_name: []const u8,
};

pub const data = [_]Jamo{
    .{ .code = 0x1100, .short_name = "G" },
    .{ .code = 0x1101, .short_name = "GG" },
    .{ .code = 0x1102, .short_name = "N" },
    .{ .code = 0x1103, .short_name = "D" },
    .{ .code = 0x1104, .short_name = "DD" },
    .{ .code = 0x1105, .short_name = "R" },
    .{ .code = 0x1106, .short_name = "M" },
    .{ .code = 0x1107, .short_name = "B" },
    .{ .code = 0x1108, .short_name = "BB" },
    .{ .code = 0x1109, .short_name = "S" },
    .{ .code = 0x110A, .short_name = "SS" },
    .{ .code = 0x110B, .short_name = "" },
    .{ .code = 0x110C, .short_name = "J" },
    .{ .code = 0x110D, .short_name = "JJ" },
    .{ .code = 0x110E, .short_name = "C" },
    .{ .code = 0x110F, .short_name = "K" },
    .{ .code = 0x1110, .short_name = "T" },
    .{ .code = 0x1111, .short_name = "P" },
    .{ .code = 0x1112, .short_name = "H" },
    .{ .code = 0x1161, .short_name = "A" },
    .{ .code = 0x1162, .short_name = "AE" },
    .{ .code = 0x1163, .short_name = "YA" },
    .{ .code = 0x1164, .short_name = "YAE" },
    .{ .code = 0x1165, .short_name = "EO" },
    .{ .code = 0x1166, .short_name = "E" },
    .{ .code = 0x1167, .short_name = "YEO" },
    .{ .code = 0x1168, .short_name = "YE" },
    .{ .code = 0x1169, .short_name = "O" },
    .{ .code = 0x116A, .short_name = "WA" },
    .{ .code = 0x116B, .short_name = "WAE" },
    .{ .code = 0x116C, .short_name = "OE" },
    .{ .code = 0x116D, .short_name = "YO" },
    .{ .code = 0x116E, .short_name = "U" },
    .{ .code = 0x116F, .short_name = "WEO" },
    .{ .code = 0x1170, .short_name = "WE" },
    .{ .code = 0x1171, .short_name = "WI" },
    .{ .code = 0x1172, .short_name = "YU" },
    .{ .code = 0x1173, .short_name = "EU" },
    .{ .code = 0x1174, .short_name = "YI" },
    .{ .code = 0x1175, .short_name = "I" },
    .{ .code = 0x11A8, .short_name = "G" },
    .{ .code = 0x11A9, .short_name = "GG" },
    .{ .code = 0x11AA, .short_name = "GS" },
    .{ .code = 0x11AB, .short_name = "N" },
    .{ .code = 0x11AC, .short_name = "NJ" },
    .{ .code = 0x11AD, .short_name = "NH" },
    .{ .code = 0x11AE, .short_name = "D" },
    .{ .code = 0x11AF, .short_name = "L" },
    .{ .code = 0x11B0, .short_name = "LG" },
    .{ .code = 0x11B1, .short_name = "LM" },
    .{ .code = 0x11B2, .short_name = "LB" },
    .{ .code = 0x11B3, .short_name = "LS" },
    .{ .code = 0x11B4, .short_name = "LT" },
    .{ .code = 0x11B5, .short_name = "LP" },
    .{ .code = 0x11B6, .short_name = "LH" },
    .{ .code = 0x11B7, .short_name = "M" },
    .{ .code = 0x11B8, .short_name = "B" },
    .{ .code = 0x11B9, .short_name = "BS" },
    .{ .code = 0x11BA, .short_name = "S" },
    .{ .code = 0x11BB, .short_name = "SS" },
    .{ .code = 0x11BC, .short_name = "NG" },
    .{ .code = 0x11BD, .short_name = "J" },
    .{ .code = 0x11BE, .short_name = "C" },
    .{ .code = 0x11BF, .short_name = "K" },
    .{ .code = 0x11C0, .short_name = "T" },
    .{ .code = 0x11C1, .short_name = "P" },
    .{ .code = 0x11C2, .short_name = "H" },
};
