// This file is part of the Unicode Character Database
// For documentation, see http://www.unicode.org/reports/tr44/
//
// Based on the source file: https://unicode.org/Public/15.1.0/ucd/NameAliases.txt
//
// zig fmt: off

pub const NameAlias = struct {
    code: u21,
    alias: []const u8,
    type: enum {
        correction,
        control,
        alternate,
        figment,
        abbreviation,
    },
};

pub const data = [_]NameAlias{
    .{ .code = 0x0000, .alias = "NULL", .type = .control },
    .{ .code = 0x0000, .alias = "NUL", .type = .abbreviation },
    .{ .code = 0x0001, .alias = "START OF HEADING", .type = .control },
    .{ .code = 0x0001, .alias = "SOH", .type = .abbreviation },
    .{ .code = 0x0002, .alias = "START OF TEXT", .type = .control },
    .{ .code = 0x0002, .alias = "STX", .type = .abbreviation },
    .{ .code = 0x0003, .alias = "END OF TEXT", .type = .control },
    .{ .code = 0x0003, .alias = "ETX", .type = .abbreviation },
    .{ .code = 0x0004, .alias = "END OF TRANSMISSION", .type = .control },
    .{ .code = 0x0004, .alias = "EOT", .type = .abbreviation },
    .{ .code = 0x0005, .alias = "ENQUIRY", .type = .control },
    .{ .code = 0x0005, .alias = "ENQ", .type = .abbreviation },
    .{ .code = 0x0006, .alias = "ACKNOWLEDGE", .type = .control },
    .{ .code = 0x0006, .alias = "ACK", .type = .abbreviation },
    .{ .code = 0x0007, .alias = "ALERT", .type = .control },
    .{ .code = 0x0007, .alias = "BEL", .type = .abbreviation },
    .{ .code = 0x0008, .alias = "BACKSPACE", .type = .control },
    .{ .code = 0x0008, .alias = "BS", .type = .abbreviation },
    .{ .code = 0x0009, .alias = "CHARACTER TABULATION", .type = .control },
    .{ .code = 0x0009, .alias = "HORIZONTAL TABULATION", .type = .control },
    .{ .code = 0x0009, .alias = "HT", .type = .abbreviation },
    .{ .code = 0x0009, .alias = "TAB", .type = .abbreviation },
    .{ .code = 0x000A, .alias = "LINE FEED", .type = .control },
    .{ .code = 0x000A, .alias = "NEW LINE", .type = .control },
    .{ .code = 0x000A, .alias = "END OF LINE", .type = .control },
    .{ .code = 0x000A, .alias = "LF", .type = .abbreviation },
    .{ .code = 0x000A, .alias = "NL", .type = .abbreviation },
    .{ .code = 0x000A, .alias = "EOL", .type = .abbreviation },
    .{ .code = 0x000B, .alias = "LINE TABULATION", .type = .control },
    .{ .code = 0x000B, .alias = "VERTICAL TABULATION", .type = .control },
    .{ .code = 0x000B, .alias = "VT", .type = .abbreviation },
    .{ .code = 0x000C, .alias = "FORM FEED", .type = .control },
    .{ .code = 0x000C, .alias = "FF", .type = .abbreviation },
    .{ .code = 0x000D, .alias = "CARRIAGE RETURN", .type = .control },
    .{ .code = 0x000D, .alias = "CR", .type = .abbreviation },
    .{ .code = 0x000E, .alias = "SHIFT OUT", .type = .control },
    .{ .code = 0x000E, .alias = "LOCKING-SHIFT ONE", .type = .control },
    .{ .code = 0x000E, .alias = "SO", .type = .abbreviation },
    .{ .code = 0x000F, .alias = "SHIFT IN", .type = .control },
    .{ .code = 0x000F, .alias = "LOCKING-SHIFT ZERO", .type = .control },
    .{ .code = 0x000F, .alias = "SI", .type = .abbreviation },
    .{ .code = 0x0010, .alias = "DATA LINK ESCAPE", .type = .control },
    .{ .code = 0x0010, .alias = "DLE", .type = .abbreviation },
    .{ .code = 0x0011, .alias = "DEVICE CONTROL ONE", .type = .control },
    .{ .code = 0x0011, .alias = "DC1", .type = .abbreviation },
    .{ .code = 0x0012, .alias = "DEVICE CONTROL TWO", .type = .control },
    .{ .code = 0x0012, .alias = "DC2", .type = .abbreviation },
    .{ .code = 0x0013, .alias = "DEVICE CONTROL THREE", .type = .control },
    .{ .code = 0x0013, .alias = "DC3", .type = .abbreviation },
    .{ .code = 0x0014, .alias = "DEVICE CONTROL FOUR", .type = .control },
    .{ .code = 0x0014, .alias = "DC4", .type = .abbreviation },
    .{ .code = 0x0015, .alias = "NEGATIVE ACKNOWLEDGE", .type = .control },
    .{ .code = 0x0015, .alias = "NAK", .type = .abbreviation },
    .{ .code = 0x0016, .alias = "SYNCHRONOUS IDLE", .type = .control },
    .{ .code = 0x0016, .alias = "SYN", .type = .abbreviation },
    .{ .code = 0x0017, .alias = "END OF TRANSMISSION BLOCK", .type = .control },
    .{ .code = 0x0017, .alias = "ETB", .type = .abbreviation },
    .{ .code = 0x0018, .alias = "CANCEL", .type = .control },
    .{ .code = 0x0018, .alias = "CAN", .type = .abbreviation },
    .{ .code = 0x0019, .alias = "END OF MEDIUM", .type = .control },
    .{ .code = 0x0019, .alias = "EOM", .type = .abbreviation },
    .{ .code = 0x0019, .alias = "EM", .type = .abbreviation },
    .{ .code = 0x001A, .alias = "SUBSTITUTE", .type = .control },
    .{ .code = 0x001A, .alias = "SUB", .type = .abbreviation },
    .{ .code = 0x001B, .alias = "ESCAPE", .type = .control },
    .{ .code = 0x001B, .alias = "ESC", .type = .abbreviation },
    .{ .code = 0x001C, .alias = "INFORMATION SEPARATOR FOUR", .type = .control },
    .{ .code = 0x001C, .alias = "FILE SEPARATOR", .type = .control },
    .{ .code = 0x001C, .alias = "FS", .type = .abbreviation },
    .{ .code = 0x001D, .alias = "INFORMATION SEPARATOR THREE", .type = .control },
    .{ .code = 0x001D, .alias = "GROUP SEPARATOR", .type = .control },
    .{ .code = 0x001D, .alias = "GS", .type = .abbreviation },
    .{ .code = 0x001E, .alias = "INFORMATION SEPARATOR TWO", .type = .control },
    .{ .code = 0x001E, .alias = "RECORD SEPARATOR", .type = .control },
    .{ .code = 0x001E, .alias = "RS", .type = .abbreviation },
    .{ .code = 0x001F, .alias = "INFORMATION SEPARATOR ONE", .type = .control },
    .{ .code = 0x001F, .alias = "UNIT SEPARATOR", .type = .control },
    .{ .code = 0x001F, .alias = "US", .type = .abbreviation },
    .{ .code = 0x0020, .alias = "SP", .type = .abbreviation },
    .{ .code = 0x007F, .alias = "DELETE", .type = .control },
    .{ .code = 0x007F, .alias = "DEL", .type = .abbreviation },
    .{ .code = 0x0080, .alias = "PADDING CHARACTER", .type = .figment },
    .{ .code = 0x0080, .alias = "PAD", .type = .abbreviation },
    .{ .code = 0x0081, .alias = "HIGH OCTET PRESET", .type = .figment },
    .{ .code = 0x0081, .alias = "HOP", .type = .abbreviation },
    .{ .code = 0x0082, .alias = "BREAK PERMITTED HERE", .type = .control },
    .{ .code = 0x0082, .alias = "BPH", .type = .abbreviation },
    .{ .code = 0x0083, .alias = "NO BREAK HERE", .type = .control },
    .{ .code = 0x0083, .alias = "NBH", .type = .abbreviation },
    .{ .code = 0x0084, .alias = "INDEX", .type = .control },
    .{ .code = 0x0084, .alias = "IND", .type = .abbreviation },
    .{ .code = 0x0085, .alias = "NEXT LINE", .type = .control },
    .{ .code = 0x0085, .alias = "NEL", .type = .abbreviation },
    .{ .code = 0x0086, .alias = "START OF SELECTED AREA", .type = .control },
    .{ .code = 0x0086, .alias = "SSA", .type = .abbreviation },
    .{ .code = 0x0087, .alias = "END OF SELECTED AREA", .type = .control },
    .{ .code = 0x0087, .alias = "ESA", .type = .abbreviation },
    .{ .code = 0x0088, .alias = "CHARACTER TABULATION SET", .type = .control },
    .{ .code = 0x0088, .alias = "HORIZONTAL TABULATION SET", .type = .control },
    .{ .code = 0x0088, .alias = "HTS", .type = .abbreviation },
    .{ .code = 0x0089, .alias = "CHARACTER TABULATION WITH JUSTIFICATION", .type = .control },
    .{ .code = 0x0089, .alias = "HORIZONTAL TABULATION WITH JUSTIFICATION", .type = .control },
    .{ .code = 0x0089, .alias = "HTJ", .type = .abbreviation },
    .{ .code = 0x008A, .alias = "LINE TABULATION SET", .type = .control },
    .{ .code = 0x008A, .alias = "VERTICAL TABULATION SET", .type = .control },
    .{ .code = 0x008A, .alias = "VTS", .type = .abbreviation },
    .{ .code = 0x008B, .alias = "PARTIAL LINE FORWARD", .type = .control },
    .{ .code = 0x008B, .alias = "PARTIAL LINE DOWN", .type = .control },
    .{ .code = 0x008B, .alias = "PLD", .type = .abbreviation },
    .{ .code = 0x008C, .alias = "PARTIAL LINE BACKWARD", .type = .control },
    .{ .code = 0x008C, .alias = "PARTIAL LINE UP", .type = .control },
    .{ .code = 0x008C, .alias = "PLU", .type = .abbreviation },
    .{ .code = 0x008D, .alias = "REVERSE LINE FEED", .type = .control },
    .{ .code = 0x008D, .alias = "REVERSE INDEX", .type = .control },
    .{ .code = 0x008D, .alias = "RI", .type = .abbreviation },
    .{ .code = 0x008E, .alias = "SINGLE SHIFT TWO", .type = .control },
    .{ .code = 0x008E, .alias = "SINGLE-SHIFT-2", .type = .control },
    .{ .code = 0x008E, .alias = "SS2", .type = .abbreviation },
    .{ .code = 0x008F, .alias = "SINGLE SHIFT THREE", .type = .control },
    .{ .code = 0x008F, .alias = "SINGLE-SHIFT-3", .type = .control },
    .{ .code = 0x008F, .alias = "SS3", .type = .abbreviation },
    .{ .code = 0x0090, .alias = "DEVICE CONTROL STRING", .type = .control },
    .{ .code = 0x0090, .alias = "DCS", .type = .abbreviation },
    .{ .code = 0x0091, .alias = "PRIVATE USE ONE", .type = .control },
    .{ .code = 0x0091, .alias = "PRIVATE USE-1", .type = .control },
    .{ .code = 0x0091, .alias = "PU1", .type = .abbreviation },
    .{ .code = 0x0092, .alias = "PRIVATE USE TWO", .type = .control },
    .{ .code = 0x0092, .alias = "PRIVATE USE-2", .type = .control },
    .{ .code = 0x0092, .alias = "PU2", .type = .abbreviation },
    .{ .code = 0x0093, .alias = "SET TRANSMIT STATE", .type = .control },
    .{ .code = 0x0093, .alias = "STS", .type = .abbreviation },
    .{ .code = 0x0094, .alias = "CANCEL CHARACTER", .type = .control },
    .{ .code = 0x0094, .alias = "CCH", .type = .abbreviation },
    .{ .code = 0x0095, .alias = "MESSAGE WAITING", .type = .control },
    .{ .code = 0x0095, .alias = "MW", .type = .abbreviation },
    .{ .code = 0x0096, .alias = "START OF GUARDED AREA", .type = .control },
    .{ .code = 0x0096, .alias = "START OF PROTECTED AREA", .type = .control },
    .{ .code = 0x0096, .alias = "SPA", .type = .abbreviation },
    .{ .code = 0x0097, .alias = "END OF GUARDED AREA", .type = .control },
    .{ .code = 0x0097, .alias = "END OF PROTECTED AREA", .type = .control },
    .{ .code = 0x0097, .alias = "EPA", .type = .abbreviation },
    .{ .code = 0x0098, .alias = "START OF STRING", .type = .control },
    .{ .code = 0x0098, .alias = "SOS", .type = .abbreviation },
    .{ .code = 0x0099, .alias = "SINGLE GRAPHIC CHARACTER INTRODUCER", .type = .figment },
    .{ .code = 0x0099, .alias = "SGC", .type = .abbreviation },
    .{ .code = 0x009A, .alias = "SINGLE CHARACTER INTRODUCER", .type = .control },
    .{ .code = 0x009A, .alias = "SCI", .type = .abbreviation },
    .{ .code = 0x009B, .alias = "CONTROL SEQUENCE INTRODUCER", .type = .control },
    .{ .code = 0x009B, .alias = "CSI", .type = .abbreviation },
    .{ .code = 0x009C, .alias = "STRING TERMINATOR", .type = .control },
    .{ .code = 0x009C, .alias = "ST", .type = .abbreviation },
    .{ .code = 0x009D, .alias = "OPERATING SYSTEM COMMAND", .type = .control },
    .{ .code = 0x009D, .alias = "OSC", .type = .abbreviation },
    .{ .code = 0x009E, .alias = "PRIVACY MESSAGE", .type = .control },
    .{ .code = 0x009E, .alias = "PM", .type = .abbreviation },
    .{ .code = 0x009F, .alias = "APPLICATION PROGRAM COMMAND", .type = .control },
    .{ .code = 0x009F, .alias = "APC", .type = .abbreviation },
    .{ .code = 0x00A0, .alias = "NBSP", .type = .abbreviation },
    .{ .code = 0x00AD, .alias = "SHY", .type = .abbreviation },
    .{ .code = 0x01A2, .alias = "LATIN CAPITAL LETTER GHA", .type = .correction },
    .{ .code = 0x01A3, .alias = "LATIN SMALL LETTER GHA", .type = .correction },
    .{ .code = 0x034F, .alias = "CGJ", .type = .abbreviation },
    .{ .code = 0x0616, .alias = "ARABIC SMALL HIGH LIGATURE ALEF WITH YEH BARREE", .type = .correction },
    .{ .code = 0x061C, .alias = "ALM", .type = .abbreviation },
    .{ .code = 0x0709, .alias = "SYRIAC SUBLINEAR COLON SKEWED LEFT", .type = .correction },
    .{ .code = 0x0CDE, .alias = "KANNADA LETTER LLLA", .type = .correction },
    .{ .code = 0x0E9D, .alias = "LAO LETTER FO FON", .type = .correction },
    .{ .code = 0x0E9F, .alias = "LAO LETTER FO FAY", .type = .correction },
    .{ .code = 0x0EA3, .alias = "LAO LETTER RO", .type = .correction },
    .{ .code = 0x0EA5, .alias = "LAO LETTER LO", .type = .correction },
    .{ .code = 0x0FD0, .alias = "TIBETAN MARK BKA- SHOG GI MGO RGYAN", .type = .correction },
    .{ .code = 0x11EC, .alias = "HANGUL JONGSEONG YESIEUNG-KIYEOK", .type = .correction },
    .{ .code = 0x11ED, .alias = "HANGUL JONGSEONG YESIEUNG-SSANGKIYEOK", .type = .correction },
    .{ .code = 0x11EE, .alias = "HANGUL JONGSEONG SSANGYESIEUNG", .type = .correction },
    .{ .code = 0x11EF, .alias = "HANGUL JONGSEONG YESIEUNG-KHIEUKH", .type = .correction },
    .{ .code = 0x180B, .alias = "FVS1", .type = .abbreviation },
    .{ .code = 0x180C, .alias = "FVS2", .type = .abbreviation },
    .{ .code = 0x180D, .alias = "FVS3", .type = .abbreviation },
    .{ .code = 0x180E, .alias = "MVS", .type = .abbreviation },
    .{ .code = 0x180F, .alias = "FVS4", .type = .abbreviation },
    .{ .code = 0x1BBD, .alias = "SUNDANESE LETTER ARCHAIC I", .type = .correction },
    .{ .code = 0x200B, .alias = "ZWSP", .type = .abbreviation },
    .{ .code = 0x200C, .alias = "ZWNJ", .type = .abbreviation },
    .{ .code = 0x200D, .alias = "ZWJ", .type = .abbreviation },
    .{ .code = 0x200E, .alias = "LRM", .type = .abbreviation },
    .{ .code = 0x200F, .alias = "RLM", .type = .abbreviation },
    .{ .code = 0x202A, .alias = "LRE", .type = .abbreviation },
    .{ .code = 0x202B, .alias = "RLE", .type = .abbreviation },
    .{ .code = 0x202C, .alias = "PDF", .type = .abbreviation },
    .{ .code = 0x202D, .alias = "LRO", .type = .abbreviation },
    .{ .code = 0x202E, .alias = "RLO", .type = .abbreviation },
    .{ .code = 0x202F, .alias = "NNBSP", .type = .abbreviation },
    .{ .code = 0x205F, .alias = "MMSP", .type = .abbreviation },
    .{ .code = 0x2060, .alias = "WJ", .type = .abbreviation },
    .{ .code = 0x2066, .alias = "LRI", .type = .abbreviation },
    .{ .code = 0x2067, .alias = "RLI", .type = .abbreviation },
    .{ .code = 0x2068, .alias = "FSI", .type = .abbreviation },
    .{ .code = 0x2069, .alias = "PDI", .type = .abbreviation },
    .{ .code = 0x2118, .alias = "WEIERSTRASS ELLIPTIC FUNCTION", .type = .correction },
    .{ .code = 0x2448, .alias = "MICR ON US SYMBOL", .type = .correction },
    .{ .code = 0x2449, .alias = "MICR DASH SYMBOL", .type = .correction },
    .{ .code = 0x2B7A, .alias = "LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE", .type = .correction },
    .{ .code = 0x2B7C, .alias = "RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE", .type = .correction },
    .{ .code = 0xA015, .alias = "YI SYLLABLE ITERATION MARK", .type = .correction },
    .{ .code = 0xAA6E, .alias = "MYANMAR LETTER KHAMTI LLA", .type = .correction },
    .{ .code = 0xFE00, .alias = "VS1", .type = .abbreviation },
    .{ .code = 0xFE01, .alias = "VS2", .type = .abbreviation },
    .{ .code = 0xFE02, .alias = "VS3", .type = .abbreviation },
    .{ .code = 0xFE03, .alias = "VS4", .type = .abbreviation },
    .{ .code = 0xFE04, .alias = "VS5", .type = .abbreviation },
    .{ .code = 0xFE05, .alias = "VS6", .type = .abbreviation },
    .{ .code = 0xFE06, .alias = "VS7", .type = .abbreviation },
    .{ .code = 0xFE07, .alias = "VS8", .type = .abbreviation },
    .{ .code = 0xFE08, .alias = "VS9", .type = .abbreviation },
    .{ .code = 0xFE09, .alias = "VS10", .type = .abbreviation },
    .{ .code = 0xFE0A, .alias = "VS11", .type = .abbreviation },
    .{ .code = 0xFE0B, .alias = "VS12", .type = .abbreviation },
    .{ .code = 0xFE0C, .alias = "VS13", .type = .abbreviation },
    .{ .code = 0xFE0D, .alias = "VS14", .type = .abbreviation },
    .{ .code = 0xFE0E, .alias = "VS15", .type = .abbreviation },
    .{ .code = 0xFE0F, .alias = "VS16", .type = .abbreviation },
    .{ .code = 0xFE18, .alias = "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET", .type = .correction },
    .{ .code = 0xFEFF, .alias = "BYTE ORDER MARK", .type = .alternate },
    .{ .code = 0xFEFF, .alias = "BOM", .type = .abbreviation },
    .{ .code = 0xFEFF, .alias = "ZWNBSP", .type = .abbreviation },
    .{ .code = 0x122D4, .alias = "CUNEIFORM SIGN NU11 TENU", .type = .correction },
    .{ .code = 0x122D5, .alias = "CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR", .type = .correction },
    .{ .code = 0x16E56, .alias = "MEDEFAIDRIN CAPITAL LETTER H", .type = .correction },
    .{ .code = 0x16E57, .alias = "MEDEFAIDRIN CAPITAL LETTER NG", .type = .correction },
    .{ .code = 0x16E76, .alias = "MEDEFAIDRIN SMALL LETTER H", .type = .correction },
    .{ .code = 0x16E77, .alias = "MEDEFAIDRIN SMALL LETTER NG", .type = .correction },
    .{ .code = 0x1B001, .alias = "HENTAIGANA LETTER E-1", .type = .correction },
    .{ .code = 0x1D0C5, .alias = "BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS", .type = .correction },
    .{ .code = 0xE0100, .alias = "VS17", .type = .abbreviation },
    .{ .code = 0xE0101, .alias = "VS18", .type = .abbreviation },
    .{ .code = 0xE0102, .alias = "VS19", .type = .abbreviation },
    .{ .code = 0xE0103, .alias = "VS20", .type = .abbreviation },
    .{ .code = 0xE0104, .alias = "VS21", .type = .abbreviation },
    .{ .code = 0xE0105, .alias = "VS22", .type = .abbreviation },
    .{ .code = 0xE0106, .alias = "VS23", .type = .abbreviation },
    .{ .code = 0xE0107, .alias = "VS24", .type = .abbreviation },
    .{ .code = 0xE0108, .alias = "VS25", .type = .abbreviation },
    .{ .code = 0xE0109, .alias = "VS26", .type = .abbreviation },
    .{ .code = 0xE010A, .alias = "VS27", .type = .abbreviation },
    .{ .code = 0xE010B, .alias = "VS28", .type = .abbreviation },
    .{ .code = 0xE010C, .alias = "VS29", .type = .abbreviation },
    .{ .code = 0xE010D, .alias = "VS30", .type = .abbreviation },
    .{ .code = 0xE010E, .alias = "VS31", .type = .abbreviation },
    .{ .code = 0xE010F, .alias = "VS32", .type = .abbreviation },
    .{ .code = 0xE0110, .alias = "VS33", .type = .abbreviation },
    .{ .code = 0xE0111, .alias = "VS34", .type = .abbreviation },
    .{ .code = 0xE0112, .alias = "VS35", .type = .abbreviation },
    .{ .code = 0xE0113, .alias = "VS36", .type = .abbreviation },
    .{ .code = 0xE0114, .alias = "VS37", .type = .abbreviation },
    .{ .code = 0xE0115, .alias = "VS38", .type = .abbreviation },
    .{ .code = 0xE0116, .alias = "VS39", .type = .abbreviation },
    .{ .code = 0xE0117, .alias = "VS40", .type = .abbreviation },
    .{ .code = 0xE0118, .alias = "VS41", .type = .abbreviation },
    .{ .code = 0xE0119, .alias = "VS42", .type = .abbreviation },
    .{ .code = 0xE011A, .alias = "VS43", .type = .abbreviation },
    .{ .code = 0xE011B, .alias = "VS44", .type = .abbreviation },
    .{ .code = 0xE011C, .alias = "VS45", .type = .abbreviation },
    .{ .code = 0xE011D, .alias = "VS46", .type = .abbreviation },
    .{ .code = 0xE011E, .alias = "VS47", .type = .abbreviation },
    .{ .code = 0xE011F, .alias = "VS48", .type = .abbreviation },
    .{ .code = 0xE0120, .alias = "VS49", .type = .abbreviation },
    .{ .code = 0xE0121, .alias = "VS50", .type = .abbreviation },
    .{ .code = 0xE0122, .alias = "VS51", .type = .abbreviation },
    .{ .code = 0xE0123, .alias = "VS52", .type = .abbreviation },
    .{ .code = 0xE0124, .alias = "VS53", .type = .abbreviation },
    .{ .code = 0xE0125, .alias = "VS54", .type = .abbreviation },
    .{ .code = 0xE0126, .alias = "VS55", .type = .abbreviation },
    .{ .code = 0xE0127, .alias = "VS56", .type = .abbreviation },
    .{ .code = 0xE0128, .alias = "VS57", .type = .abbreviation },
    .{ .code = 0xE0129, .alias = "VS58", .type = .abbreviation },
    .{ .code = 0xE012A, .alias = "VS59", .type = .abbreviation },
    .{ .code = 0xE012B, .alias = "VS60", .type = .abbreviation },
    .{ .code = 0xE012C, .alias = "VS61", .type = .abbreviation },
    .{ .code = 0xE012D, .alias = "VS62", .type = .abbreviation },
    .{ .code = 0xE012E, .alias = "VS63", .type = .abbreviation },
    .{ .code = 0xE012F, .alias = "VS64", .type = .abbreviation },
    .{ .code = 0xE0130, .alias = "VS65", .type = .abbreviation },
    .{ .code = 0xE0131, .alias = "VS66", .type = .abbreviation },
    .{ .code = 0xE0132, .alias = "VS67", .type = .abbreviation },
    .{ .code = 0xE0133, .alias = "VS68", .type = .abbreviation },
    .{ .code = 0xE0134, .alias = "VS69", .type = .abbreviation },
    .{ .code = 0xE0135, .alias = "VS70", .type = .abbreviation },
    .{ .code = 0xE0136, .alias = "VS71", .type = .abbreviation },
    .{ .code = 0xE0137, .alias = "VS72", .type = .abbreviation },
    .{ .code = 0xE0138, .alias = "VS73", .type = .abbreviation },
    .{ .code = 0xE0139, .alias = "VS74", .type = .abbreviation },
    .{ .code = 0xE013A, .alias = "VS75", .type = .abbreviation },
    .{ .code = 0xE013B, .alias = "VS76", .type = .abbreviation },
    .{ .code = 0xE013C, .alias = "VS77", .type = .abbreviation },
    .{ .code = 0xE013D, .alias = "VS78", .type = .abbreviation },
    .{ .code = 0xE013E, .alias = "VS79", .type = .abbreviation },
    .{ .code = 0xE013F, .alias = "VS80", .type = .abbreviation },
    .{ .code = 0xE0140, .alias = "VS81", .type = .abbreviation },
    .{ .code = 0xE0141, .alias = "VS82", .type = .abbreviation },
    .{ .code = 0xE0142, .alias = "VS83", .type = .abbreviation },
    .{ .code = 0xE0143, .alias = "VS84", .type = .abbreviation },
    .{ .code = 0xE0144, .alias = "VS85", .type = .abbreviation },
    .{ .code = 0xE0145, .alias = "VS86", .type = .abbreviation },
    .{ .code = 0xE0146, .alias = "VS87", .type = .abbreviation },
    .{ .code = 0xE0147, .alias = "VS88", .type = .abbreviation },
    .{ .code = 0xE0148, .alias = "VS89", .type = .abbreviation },
    .{ .code = 0xE0149, .alias = "VS90", .type = .abbreviation },
    .{ .code = 0xE014A, .alias = "VS91", .type = .abbreviation },
    .{ .code = 0xE014B, .alias = "VS92", .type = .abbreviation },
    .{ .code = 0xE014C, .alias = "VS93", .type = .abbreviation },
    .{ .code = 0xE014D, .alias = "VS94", .type = .abbreviation },
    .{ .code = 0xE014E, .alias = "VS95", .type = .abbreviation },
    .{ .code = 0xE014F, .alias = "VS96", .type = .abbreviation },
    .{ .code = 0xE0150, .alias = "VS97", .type = .abbreviation },
    .{ .code = 0xE0151, .alias = "VS98", .type = .abbreviation },
    .{ .code = 0xE0152, .alias = "VS99", .type = .abbreviation },
    .{ .code = 0xE0153, .alias = "VS100", .type = .abbreviation },
    .{ .code = 0xE0154, .alias = "VS101", .type = .abbreviation },
    .{ .code = 0xE0155, .alias = "VS102", .type = .abbreviation },
    .{ .code = 0xE0156, .alias = "VS103", .type = .abbreviation },
    .{ .code = 0xE0157, .alias = "VS104", .type = .abbreviation },
    .{ .code = 0xE0158, .alias = "VS105", .type = .abbreviation },
    .{ .code = 0xE0159, .alias = "VS106", .type = .abbreviation },
    .{ .code = 0xE015A, .alias = "VS107", .type = .abbreviation },
    .{ .code = 0xE015B, .alias = "VS108", .type = .abbreviation },
    .{ .code = 0xE015C, .alias = "VS109", .type = .abbreviation },
    .{ .code = 0xE015D, .alias = "VS110", .type = .abbreviation },
    .{ .code = 0xE015E, .alias = "VS111", .type = .abbreviation },
    .{ .code = 0xE015F, .alias = "VS112", .type = .abbreviation },
    .{ .code = 0xE0160, .alias = "VS113", .type = .abbreviation },
    .{ .code = 0xE0161, .alias = "VS114", .type = .abbreviation },
    .{ .code = 0xE0162, .alias = "VS115", .type = .abbreviation },
    .{ .code = 0xE0163, .alias = "VS116", .type = .abbreviation },
    .{ .code = 0xE0164, .alias = "VS117", .type = .abbreviation },
    .{ .code = 0xE0165, .alias = "VS118", .type = .abbreviation },
    .{ .code = 0xE0166, .alias = "VS119", .type = .abbreviation },
    .{ .code = 0xE0167, .alias = "VS120", .type = .abbreviation },
    .{ .code = 0xE0168, .alias = "VS121", .type = .abbreviation },
    .{ .code = 0xE0169, .alias = "VS122", .type = .abbreviation },
    .{ .code = 0xE016A, .alias = "VS123", .type = .abbreviation },
    .{ .code = 0xE016B, .alias = "VS124", .type = .abbreviation },
    .{ .code = 0xE016C, .alias = "VS125", .type = .abbreviation },
    .{ .code = 0xE016D, .alias = "VS126", .type = .abbreviation },
    .{ .code = 0xE016E, .alias = "VS127", .type = .abbreviation },
    .{ .code = 0xE016F, .alias = "VS128", .type = .abbreviation },
    .{ .code = 0xE0170, .alias = "VS129", .type = .abbreviation },
    .{ .code = 0xE0171, .alias = "VS130", .type = .abbreviation },
    .{ .code = 0xE0172, .alias = "VS131", .type = .abbreviation },
    .{ .code = 0xE0173, .alias = "VS132", .type = .abbreviation },
    .{ .code = 0xE0174, .alias = "VS133", .type = .abbreviation },
    .{ .code = 0xE0175, .alias = "VS134", .type = .abbreviation },
    .{ .code = 0xE0176, .alias = "VS135", .type = .abbreviation },
    .{ .code = 0xE0177, .alias = "VS136", .type = .abbreviation },
    .{ .code = 0xE0178, .alias = "VS137", .type = .abbreviation },
    .{ .code = 0xE0179, .alias = "VS138", .type = .abbreviation },
    .{ .code = 0xE017A, .alias = "VS139", .type = .abbreviation },
    .{ .code = 0xE017B, .alias = "VS140", .type = .abbreviation },
    .{ .code = 0xE017C, .alias = "VS141", .type = .abbreviation },
    .{ .code = 0xE017D, .alias = "VS142", .type = .abbreviation },
    .{ .code = 0xE017E, .alias = "VS143", .type = .abbreviation },
    .{ .code = 0xE017F, .alias = "VS144", .type = .abbreviation },
    .{ .code = 0xE0180, .alias = "VS145", .type = .abbreviation },
    .{ .code = 0xE0181, .alias = "VS146", .type = .abbreviation },
    .{ .code = 0xE0182, .alias = "VS147", .type = .abbreviation },
    .{ .code = 0xE0183, .alias = "VS148", .type = .abbreviation },
    .{ .code = 0xE0184, .alias = "VS149", .type = .abbreviation },
    .{ .code = 0xE0185, .alias = "VS150", .type = .abbreviation },
    .{ .code = 0xE0186, .alias = "VS151", .type = .abbreviation },
    .{ .code = 0xE0187, .alias = "VS152", .type = .abbreviation },
    .{ .code = 0xE0188, .alias = "VS153", .type = .abbreviation },
    .{ .code = 0xE0189, .alias = "VS154", .type = .abbreviation },
    .{ .code = 0xE018A, .alias = "VS155", .type = .abbreviation },
    .{ .code = 0xE018B, .alias = "VS156", .type = .abbreviation },
    .{ .code = 0xE018C, .alias = "VS157", .type = .abbreviation },
    .{ .code = 0xE018D, .alias = "VS158", .type = .abbreviation },
    .{ .code = 0xE018E, .alias = "VS159", .type = .abbreviation },
    .{ .code = 0xE018F, .alias = "VS160", .type = .abbreviation },
    .{ .code = 0xE0190, .alias = "VS161", .type = .abbreviation },
    .{ .code = 0xE0191, .alias = "VS162", .type = .abbreviation },
    .{ .code = 0xE0192, .alias = "VS163", .type = .abbreviation },
    .{ .code = 0xE0193, .alias = "VS164", .type = .abbreviation },
    .{ .code = 0xE0194, .alias = "VS165", .type = .abbreviation },
    .{ .code = 0xE0195, .alias = "VS166", .type = .abbreviation },
    .{ .code = 0xE0196, .alias = "VS167", .type = .abbreviation },
    .{ .code = 0xE0197, .alias = "VS168", .type = .abbreviation },
    .{ .code = 0xE0198, .alias = "VS169", .type = .abbreviation },
    .{ .code = 0xE0199, .alias = "VS170", .type = .abbreviation },
    .{ .code = 0xE019A, .alias = "VS171", .type = .abbreviation },
    .{ .code = 0xE019B, .alias = "VS172", .type = .abbreviation },
    .{ .code = 0xE019C, .alias = "VS173", .type = .abbreviation },
    .{ .code = 0xE019D, .alias = "VS174", .type = .abbreviation },
    .{ .code = 0xE019E, .alias = "VS175", .type = .abbreviation },
    .{ .code = 0xE019F, .alias = "VS176", .type = .abbreviation },
    .{ .code = 0xE01A0, .alias = "VS177", .type = .abbreviation },
    .{ .code = 0xE01A1, .alias = "VS178", .type = .abbreviation },
    .{ .code = 0xE01A2, .alias = "VS179", .type = .abbreviation },
    .{ .code = 0xE01A3, .alias = "VS180", .type = .abbreviation },
    .{ .code = 0xE01A4, .alias = "VS181", .type = .abbreviation },
    .{ .code = 0xE01A5, .alias = "VS182", .type = .abbreviation },
    .{ .code = 0xE01A6, .alias = "VS183", .type = .abbreviation },
    .{ .code = 0xE01A7, .alias = "VS184", .type = .abbreviation },
    .{ .code = 0xE01A8, .alias = "VS185", .type = .abbreviation },
    .{ .code = 0xE01A9, .alias = "VS186", .type = .abbreviation },
    .{ .code = 0xE01AA, .alias = "VS187", .type = .abbreviation },
    .{ .code = 0xE01AB, .alias = "VS188", .type = .abbreviation },
    .{ .code = 0xE01AC, .alias = "VS189", .type = .abbreviation },
    .{ .code = 0xE01AD, .alias = "VS190", .type = .abbreviation },
    .{ .code = 0xE01AE, .alias = "VS191", .type = .abbreviation },
    .{ .code = 0xE01AF, .alias = "VS192", .type = .abbreviation },
    .{ .code = 0xE01B0, .alias = "VS193", .type = .abbreviation },
    .{ .code = 0xE01B1, .alias = "VS194", .type = .abbreviation },
    .{ .code = 0xE01B2, .alias = "VS195", .type = .abbreviation },
    .{ .code = 0xE01B3, .alias = "VS196", .type = .abbreviation },
    .{ .code = 0xE01B4, .alias = "VS197", .type = .abbreviation },
    .{ .code = 0xE01B5, .alias = "VS198", .type = .abbreviation },
    .{ .code = 0xE01B6, .alias = "VS199", .type = .abbreviation },
    .{ .code = 0xE01B7, .alias = "VS200", .type = .abbreviation },
    .{ .code = 0xE01B8, .alias = "VS201", .type = .abbreviation },
    .{ .code = 0xE01B9, .alias = "VS202", .type = .abbreviation },
    .{ .code = 0xE01BA, .alias = "VS203", .type = .abbreviation },
    .{ .code = 0xE01BB, .alias = "VS204", .type = .abbreviation },
    .{ .code = 0xE01BC, .alias = "VS205", .type = .abbreviation },
    .{ .code = 0xE01BD, .alias = "VS206", .type = .abbreviation },
    .{ .code = 0xE01BE, .alias = "VS207", .type = .abbreviation },
    .{ .code = 0xE01BF, .alias = "VS208", .type = .abbreviation },
    .{ .code = 0xE01C0, .alias = "VS209", .type = .abbreviation },
    .{ .code = 0xE01C1, .alias = "VS210", .type = .abbreviation },
    .{ .code = 0xE01C2, .alias = "VS211", .type = .abbreviation },
    .{ .code = 0xE01C3, .alias = "VS212", .type = .abbreviation },
    .{ .code = 0xE01C4, .alias = "VS213", .type = .abbreviation },
    .{ .code = 0xE01C5, .alias = "VS214", .type = .abbreviation },
    .{ .code = 0xE01C6, .alias = "VS215", .type = .abbreviation },
    .{ .code = 0xE01C7, .alias = "VS216", .type = .abbreviation },
    .{ .code = 0xE01C8, .alias = "VS217", .type = .abbreviation },
    .{ .code = 0xE01C9, .alias = "VS218", .type = .abbreviation },
    .{ .code = 0xE01CA, .alias = "VS219", .type = .abbreviation },
    .{ .code = 0xE01CB, .alias = "VS220", .type = .abbreviation },
    .{ .code = 0xE01CC, .alias = "VS221", .type = .abbreviation },
    .{ .code = 0xE01CD, .alias = "VS222", .type = .abbreviation },
    .{ .code = 0xE01CE, .alias = "VS223", .type = .abbreviation },
    .{ .code = 0xE01CF, .alias = "VS224", .type = .abbreviation },
    .{ .code = 0xE01D0, .alias = "VS225", .type = .abbreviation },
    .{ .code = 0xE01D1, .alias = "VS226", .type = .abbreviation },
    .{ .code = 0xE01D2, .alias = "VS227", .type = .abbreviation },
    .{ .code = 0xE01D3, .alias = "VS228", .type = .abbreviation },
    .{ .code = 0xE01D4, .alias = "VS229", .type = .abbreviation },
    .{ .code = 0xE01D5, .alias = "VS230", .type = .abbreviation },
    .{ .code = 0xE01D6, .alias = "VS231", .type = .abbreviation },
    .{ .code = 0xE01D7, .alias = "VS232", .type = .abbreviation },
    .{ .code = 0xE01D8, .alias = "VS233", .type = .abbreviation },
    .{ .code = 0xE01D9, .alias = "VS234", .type = .abbreviation },
    .{ .code = 0xE01DA, .alias = "VS235", .type = .abbreviation },
    .{ .code = 0xE01DB, .alias = "VS236", .type = .abbreviation },
    .{ .code = 0xE01DC, .alias = "VS237", .type = .abbreviation },
    .{ .code = 0xE01DD, .alias = "VS238", .type = .abbreviation },
    .{ .code = 0xE01DE, .alias = "VS239", .type = .abbreviation },
    .{ .code = 0xE01DF, .alias = "VS240", .type = .abbreviation },
    .{ .code = 0xE01E0, .alias = "VS241", .type = .abbreviation },
    .{ .code = 0xE01E1, .alias = "VS242", .type = .abbreviation },
    .{ .code = 0xE01E2, .alias = "VS243", .type = .abbreviation },
    .{ .code = 0xE01E3, .alias = "VS244", .type = .abbreviation },
    .{ .code = 0xE01E4, .alias = "VS245", .type = .abbreviation },
    .{ .code = 0xE01E5, .alias = "VS246", .type = .abbreviation },
    .{ .code = 0xE01E6, .alias = "VS247", .type = .abbreviation },
    .{ .code = 0xE01E7, .alias = "VS248", .type = .abbreviation },
    .{ .code = 0xE01E8, .alias = "VS249", .type = .abbreviation },
    .{ .code = 0xE01E9, .alias = "VS250", .type = .abbreviation },
    .{ .code = 0xE01EA, .alias = "VS251", .type = .abbreviation },
    .{ .code = 0xE01EB, .alias = "VS252", .type = .abbreviation },
    .{ .code = 0xE01EC, .alias = "VS253", .type = .abbreviation },
    .{ .code = 0xE01ED, .alias = "VS254", .type = .abbreviation },
    .{ .code = 0xE01EE, .alias = "VS255", .type = .abbreviation },
    .{ .code = 0xE01EF, .alias = "VS256", .type = .abbreviation },
};
