// This file is part of the Unicode Character Database
// For documentation, see http://www.unicode.org/reports/tr44/
//
// Based on the source file: https://unicode.org/Public/16.0.0/ucd/ScriptExtensions.txt
//
// zig fmt: off

const ucd = @import("./lib.zig");

pub const ScriptExtension = struct {
    code: u21,
    scripts: []const ucd.Script,
};

pub const data = [_]ScriptExtension{
    .{ .code = 0x00B7, .scripts = &.{ .Avst, .Cari, .Copt, .Dupl, .Elba, .Geor, .Glag, .Gong, .Goth, .Grek, .Hani, .Latn, .Lydi, .Mahj, .Perm, .Shaw, } },
    .{ .code = 0x02BC, .scripts = &.{ .Beng, .Cyrl, .Deva, .Latn, .Lisu, .Thai, .Toto, } },
    .{ .code = 0x02C7, .scripts = &.{ .Bopo, .Latn, } },
    .{ .code = 0x2C9, .scripts = &.{ .Bopo, .Latn, } },
    .{ .code = 0x2CA, .scripts = &.{ .Bopo, .Latn, } },
    .{ .code = 0x2CB, .scripts = &.{ .Bopo, .Latn, } },
    .{ .code = 0x02CD, .scripts = &.{ .Latn, .Lisu, } },
    .{ .code = 0x02D7, .scripts = &.{ .Latn, .Thai, } },
    .{ .code = 0x02D9, .scripts = &.{ .Bopo, .Latn, } },
    .{ .code = 0x0300, .scripts = &.{ .Cher, .Copt, .Cyrl, .Grek, .Latn, .Perm, .Sunu, .Tale, } },
    .{ .code = 0x0301, .scripts = &.{ .Cher, .Cyrl, .Grek, .Latn, .Osge, .Sunu, .Tale, .Todr, } },
    .{ .code = 0x0302, .scripts = &.{ .Cher, .Cyrl, .Latn, .Tfng, } },
    .{ .code = 0x0303, .scripts = &.{ .Glag, .Latn, .Sunu, .Syrc, .Thai, } },
    .{ .code = 0x0304, .scripts = &.{ .Aghb, .Cher, .Copt, .Cyrl, .Goth, .Grek, .Latn, .Osge, .Syrc, .Tfng, .Todr, } },
    .{ .code = 0x0305, .scripts = &.{ .Copt, .Elba, .Glag, .Goth, .Kana, .Latn, } },
    .{ .code = 0x0306, .scripts = &.{ .Cyrl, .Grek, .Latn, .Perm, } },
    .{ .code = 0x0307, .scripts = &.{ .Copt, .Dupl, .Hebr, .Latn, .Perm, .Syrc, .Tale, .Tfng, .Todr, } },
    .{ .code = 0x0308, .scripts = &.{ .Armn, .Cyrl, .Dupl, .Goth, .Grek, .Hebr, .Latn, .Perm, .Syrc, .Tale, } },
    .{ .code = 0x0309, .scripts = &.{ .Latn, .Tfng, } },
    .{ .code = 0x030A, .scripts = &.{ .Dupl, .Latn, .Syrc, } },
    .{ .code = 0x030B, .scripts = &.{ .Cher, .Cyrl, .Latn, .Osge, } },
    .{ .code = 0x030C, .scripts = &.{ .Cher, .Latn, .Tale, } },
    .{ .code = 0x030D, .scripts = &.{ .Latn, .Sunu, } },
    .{ .code = 0x030E, .scripts = &.{ .Ethi, .Latn, } },
    .{ .code = 0x0310, .scripts = &.{ .Latn, .Sunu, } },
    .{ .code = 0x0311, .scripts = &.{ .Cyrl, .Latn, .Todr, } },
    .{ .code = 0x0313, .scripts = &.{ .Grek, .Latn, .Perm, .Todr, } },
    .{ .code = 0x0320, .scripts = &.{ .Latn, .Syrc, } },
    .{ .code = 0x0323, .scripts = &.{ .Cher, .Dupl, .Kana, .Latn, .Syrc, } },
    .{ .code = 0x0324, .scripts = &.{ .Cher, .Dupl, .Latn, .Syrc, } },
    .{ .code = 0x0325, .scripts = &.{ .Latn, .Syrc, } },
    .{ .code = 0x032D, .scripts = &.{ .Latn, .Sunu, .Syrc, } },
    .{ .code = 0x032E, .scripts = &.{ .Latn, .Syrc, } },
    .{ .code = 0x0330, .scripts = &.{ .Cher, .Latn, .Syrc, } },
    .{ .code = 0x0331, .scripts = &.{ .Aghb, .Cher, .Goth, .Latn, .Sunu, .Thai, } },
    .{ .code = 0x0342, .scripts = &.{ .Grek, } },
    .{ .code = 0x0345, .scripts = &.{ .Grek, } },
    .{ .code = 0x0358, .scripts = &.{ .Latn, .Osge, } },
    .{ .code = 0x035E, .scripts = &.{ .Aghb, .Latn, .Todr, } },
    .{ .code = 0x363, .scripts = &.{ .Latn, } },
    .{ .code = 0x364, .scripts = &.{ .Latn, } },
    .{ .code = 0x365, .scripts = &.{ .Latn, } },
    .{ .code = 0x366, .scripts = &.{ .Latn, } },
    .{ .code = 0x367, .scripts = &.{ .Latn, } },
    .{ .code = 0x368, .scripts = &.{ .Latn, } },
    .{ .code = 0x369, .scripts = &.{ .Latn, } },
    .{ .code = 0x36A, .scripts = &.{ .Latn, } },
    .{ .code = 0x36B, .scripts = &.{ .Latn, } },
    .{ .code = 0x36C, .scripts = &.{ .Latn, } },
    .{ .code = 0x36D, .scripts = &.{ .Latn, } },
    .{ .code = 0x36E, .scripts = &.{ .Latn, } },
    .{ .code = 0x36F, .scripts = &.{ .Latn, } },
    .{ .code = 0x0374, .scripts = &.{ .Copt, .Grek, } },
    .{ .code = 0x0375, .scripts = &.{ .Copt, .Grek, } },
    .{ .code = 0x0483, .scripts = &.{ .Cyrl, .Perm, } },
    .{ .code = 0x0484, .scripts = &.{ .Cyrl, .Glag, } },
    .{ .code = 0x485, .scripts = &.{ .Cyrl, .Latn, } },
    .{ .code = 0x486, .scripts = &.{ .Cyrl, .Latn, } },
    .{ .code = 0x0487, .scripts = &.{ .Cyrl, .Glag, } },
    .{ .code = 0x0589, .scripts = &.{ .Armn, .Geor, .Glag, } },
    .{ .code = 0x060C, .scripts = &.{ .Arab, .Gara, .Nkoo, .Rohg, .Syrc, .Thaa, .Yezi, } },
    .{ .code = 0x061B, .scripts = &.{ .Arab, .Gara, .Nkoo, .Rohg, .Syrc, .Thaa, .Yezi, } },
    .{ .code = 0x061C, .scripts = &.{ .Arab, .Syrc, .Thaa, } },
    .{ .code = 0x061F, .scripts = &.{ .Adlm, .Arab, .Gara, .Nkoo, .Rohg, .Syrc, .Thaa, .Yezi, } },
    .{ .code = 0x0640, .scripts = &.{ .Adlm, .Arab, .Mand, .Mani, .Ougr, .Phlp, .Rohg, .Sogd, .Syrc, } },
    .{ .code = 0x64B, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x64C, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x64D, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x64E, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x64F, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x650, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x651, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x652, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x653, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x654, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x655, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x660, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x661, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x662, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x663, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x664, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x665, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x666, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x667, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x668, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x669, .scripts = &.{ .Arab, .Thaa, .Yezi, } },
    .{ .code = 0x0670, .scripts = &.{ .Arab, .Syrc, } },
    .{ .code = 0x06D4, .scripts = &.{ .Arab, .Rohg, } },
    .{ .code = 0x0951, .scripts = &.{ .Beng, .Deva, .Gran, .Gujr, .Guru, .Knda, .Latn, .Mlym, .Orya, .Shrd, .Taml, .Telu, .Tirh, } },
    .{ .code = 0x0952, .scripts = &.{ .Beng, .Deva, .Gran, .Gujr, .Guru, .Knda, .Latn, .Mlym, .Orya, .Taml, .Telu, .Tirh, } },
    .{ .code = 0x0964, .scripts = &.{ .Beng, .Deva, .Dogr, .Gong, .Gonm, .Gran, .Gujr, .Guru, .Knda, .Mahj, .Mlym, .Nand, .Onao, .Orya, .Sind, .Sinh, .Sylo, .Takr, .Taml, .Telu, .Tirh, } },
    .{ .code = 0x0965, .scripts = &.{ .Beng, .Deva, .Dogr, .Gong, .Gonm, .Gran, .Gujr, .Gukh, .Guru, .Knda, .Limb, .Mahj, .Mlym, .Nand, .Onao, .Orya, .Sind, .Sinh, .Sylo, .Takr, .Taml, .Telu, .Tirh, } },
    .{ .code = 0x966, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x967, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x968, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x969, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96A, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96B, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96C, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96D, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96E, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x96F, .scripts = &.{ .Deva, .Dogr, .Kthi, .Mahj, } },
    .{ .code = 0x9E6, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9E7, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9E8, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9E9, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9EA, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9EB, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9EC, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9ED, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9EE, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0x9EF, .scripts = &.{ .Beng, .Cakm, .Sylo, } },
    .{ .code = 0xA66, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA67, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA68, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA69, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6A, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6B, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6C, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6D, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6E, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xA6F, .scripts = &.{ .Guru, .Mult, } },
    .{ .code = 0xAE6, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAE7, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAE8, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAE9, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAEA, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAEB, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAEC, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAED, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAEE, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xAEF, .scripts = &.{ .Gujr, .Khoj, } },
    .{ .code = 0xBE6, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBE7, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBE8, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBE9, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBEA, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBEB, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBEC, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBED, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBEE, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBEF, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBF0, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBF1, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xBF2, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x0BF3, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0xCE6, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCE7, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCE8, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCE9, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCEA, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCEB, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCEC, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCED, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCEE, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0xCEF, .scripts = &.{ .Knda, .Nand, .Tutg, } },
    .{ .code = 0x1040, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1041, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1042, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1043, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1044, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1045, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1046, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1047, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1048, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x1049, .scripts = &.{ .Cakm, .Mymr, .Tale, } },
    .{ .code = 0x10FB, .scripts = &.{ .Geor, .Glag, .Latn, } },
    .{ .code = 0x16EB, .scripts = &.{ .Runr, } },
    .{ .code = 0x16EC, .scripts = &.{ .Runr, } },
    .{ .code = 0x16ED, .scripts = &.{ .Runr, } },
    .{ .code = 0x1735, .scripts = &.{ .Buhd, .Hano, .Tagb, .Tglg, } },
    .{ .code = 0x1736, .scripts = &.{ .Buhd, .Hano, .Tagb, .Tglg, } },
    .{ .code = 0x1802, .scripts = &.{ .Mong, .Phag, } },
    .{ .code = 0x1803, .scripts = &.{ .Mong, .Phag, } },
    .{ .code = 0x1805, .scripts = &.{ .Mong, .Phag, } },
    .{ .code = 0x1CD0, .scripts = &.{ .Beng, .Deva, .Gran, .Knda, } },
    .{ .code = 0x1CD1, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CD2, .scripts = &.{ .Beng, .Deva, .Gran, .Knda, } },
    .{ .code = 0x1CD3, .scripts = &.{ .Deva, .Gran, .Knda, } },
    .{ .code = 0x1CD4, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CD5, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CD6, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CD7, .scripts = &.{ .Deva, .Shrd, } },
    .{ .code = 0x1CD8, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CD9, .scripts = &.{ .Deva, .Shrd, } },
    .{ .code = 0x1CDA, .scripts = &.{ .Deva, .Knda, .Mlym, .Orya, .Taml, .Telu, } },
    .{ .code = 0x1CDB, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CDC, .scripts = &.{ .Deva, .Shrd, } },
    .{ .code = 0x1CDD, .scripts = &.{ .Deva, .Shrd, } },
    .{ .code = 0x1CDE, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CDF, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE0, .scripts = &.{ .Deva, .Shrd, } },
    .{ .code = 0x1CE1, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CE2, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE3, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE4, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE5, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE6, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE7, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE8, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CE9, .scripts = &.{ .Deva, .Nand, } },
    .{ .code = 0x1CEA, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CEB, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CEC, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CED, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CEE, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CEF, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CF0, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CF1, .scripts = &.{ .Deva, } },
    .{ .code = 0x1CF2, .scripts = &.{ .Beng, .Deva, .Gran, .Knda, .Mlym, .Nand, .Orya, .Sinh, .Telu, .Tirh, .Tutg, } },
    .{ .code = 0x1CF3, .scripts = &.{ .Deva, .Gran, } },
    .{ .code = 0x1CF4, .scripts = &.{ .Deva, .Gran, .Knda, .Tutg, } },
    .{ .code = 0x1CF5, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CF6, .scripts = &.{ .Beng, .Deva, } },
    .{ .code = 0x1CF7, .scripts = &.{ .Beng, } },
    .{ .code = 0x1CF8, .scripts = &.{ .Deva, .Gran, } },
    .{ .code = 0x1CF9, .scripts = &.{ .Deva, .Gran, } },
    .{ .code = 0x1CFA, .scripts = &.{ .Nand, } },
    .{ .code = 0x1DC0, .scripts = &.{ .Grek, } },
    .{ .code = 0x1DC1, .scripts = &.{ .Grek, } },
    .{ .code = 0x1DF8, .scripts = &.{ .Cyrl, .Latn, .Syrc, } },
    .{ .code = 0x1DFA, .scripts = &.{ .Syrc, } },
    .{ .code = 0x202F, .scripts = &.{ .Latn, .Mong, .Phag, } },
    .{ .code = 0x204F, .scripts = &.{ .Adlm, .Arab, } },
    .{ .code = 0x205A, .scripts = &.{ .Cari, .Geor, .Glag, .Hung, .Lyci, .Orkh, } },
    .{ .code = 0x205D, .scripts = &.{ .Cari, .Grek, .Hung, .Mero, } },
    .{ .code = 0x20F0, .scripts = &.{ .Deva, .Gran, .Latn, } },
    .{ .code = 0x2E17, .scripts = &.{ .Copt, .Latn, } },
    .{ .code = 0x2E30, .scripts = &.{ .Avst, .Orkh, } },
    .{ .code = 0x2E31, .scripts = &.{ .Avst, .Cari, .Geor, .Hung, .Kthi, .Lydi, .Samr, } },
    .{ .code = 0x2E3C, .scripts = &.{ .Dupl, } },
    .{ .code = 0x2E41, .scripts = &.{ .Adlm, .Arab, .Hung, } },
    .{ .code = 0x2E43, .scripts = &.{ .Cyrl, .Glag, } },
    .{ .code = 0x2FF0, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF1, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF2, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF3, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF4, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF5, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF6, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF7, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF8, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FF9, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFA, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFB, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFC, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFD, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFE, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x2FFF, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x3001, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Mong, .Yiii, } },
    .{ .code = 0x3002, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Mong, .Phag, .Yiii, } },
    .{ .code = 0x3003, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x3006, .scripts = &.{ .Hani, } },
    .{ .code = 0x3008, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Mong, .Tibt, .Yiii, } },
    .{ .code = 0x3009, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Mong, .Tibt, .Yiii, } },
    .{ .code = 0x300A, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Lisu, .Mong, .Tibt, .Yiii, } },
    .{ .code = 0x300B, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Lisu, .Mong, .Tibt, .Yiii, } },
    .{ .code = 0x300C, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x300D, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x300E, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x300F, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3010, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3011, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3013, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x3014, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3015, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3016, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3017, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3018, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x3019, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x301A, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x301B, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x301C, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x301D, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x301E, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x301F, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x302A, .scripts = &.{ .Bopo, .Hani, } },
    .{ .code = 0x302B, .scripts = &.{ .Bopo, .Hani, } },
    .{ .code = 0x302C, .scripts = &.{ .Bopo, .Hani, } },
    .{ .code = 0x302D, .scripts = &.{ .Bopo, .Hani, } },
    .{ .code = 0x3030, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x3031, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3032, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3033, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3034, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3035, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3037, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0x303C, .scripts = &.{ .Hani, .Hira, .Kana, } },
    .{ .code = 0x303D, .scripts = &.{ .Hani, .Hira, .Kana, } },
    .{ .code = 0x303E, .scripts = &.{ .Hani, } },
    .{ .code = 0x303F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3099, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x309A, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x309B, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x309C, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x30A0, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x30FB, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0x30FC, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x3190, .scripts = &.{ .Hani, } },
    .{ .code = 0x3191, .scripts = &.{ .Hani, } },
    .{ .code = 0x3192, .scripts = &.{ .Hani, } },
    .{ .code = 0x3193, .scripts = &.{ .Hani, } },
    .{ .code = 0x3194, .scripts = &.{ .Hani, } },
    .{ .code = 0x3195, .scripts = &.{ .Hani, } },
    .{ .code = 0x3196, .scripts = &.{ .Hani, } },
    .{ .code = 0x3197, .scripts = &.{ .Hani, } },
    .{ .code = 0x3198, .scripts = &.{ .Hani, } },
    .{ .code = 0x3199, .scripts = &.{ .Hani, } },
    .{ .code = 0x319A, .scripts = &.{ .Hani, } },
    .{ .code = 0x319B, .scripts = &.{ .Hani, } },
    .{ .code = 0x319C, .scripts = &.{ .Hani, } },
    .{ .code = 0x319D, .scripts = &.{ .Hani, } },
    .{ .code = 0x319E, .scripts = &.{ .Hani, } },
    .{ .code = 0x319F, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C0, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C1, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C2, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C3, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C4, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C5, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C6, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C7, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C8, .scripts = &.{ .Hani, } },
    .{ .code = 0x31C9, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CA, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CB, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CC, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CD, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CE, .scripts = &.{ .Hani, } },
    .{ .code = 0x31CF, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D0, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D1, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D2, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D3, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D4, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D5, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D6, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D7, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D8, .scripts = &.{ .Hani, } },
    .{ .code = 0x31D9, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DA, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DB, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DC, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DD, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DE, .scripts = &.{ .Hani, } },
    .{ .code = 0x31DF, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E0, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E1, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E2, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E3, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E4, .scripts = &.{ .Hani, } },
    .{ .code = 0x31E5, .scripts = &.{ .Hani, } },
    .{ .code = 0x31EF, .scripts = &.{ .Hani, .Tang, } },
    .{ .code = 0x3220, .scripts = &.{ .Hani, } },
    .{ .code = 0x3221, .scripts = &.{ .Hani, } },
    .{ .code = 0x3222, .scripts = &.{ .Hani, } },
    .{ .code = 0x3223, .scripts = &.{ .Hani, } },
    .{ .code = 0x3224, .scripts = &.{ .Hani, } },
    .{ .code = 0x3225, .scripts = &.{ .Hani, } },
    .{ .code = 0x3226, .scripts = &.{ .Hani, } },
    .{ .code = 0x3227, .scripts = &.{ .Hani, } },
    .{ .code = 0x3228, .scripts = &.{ .Hani, } },
    .{ .code = 0x3229, .scripts = &.{ .Hani, } },
    .{ .code = 0x322A, .scripts = &.{ .Hani, } },
    .{ .code = 0x322B, .scripts = &.{ .Hani, } },
    .{ .code = 0x322C, .scripts = &.{ .Hani, } },
    .{ .code = 0x322D, .scripts = &.{ .Hani, } },
    .{ .code = 0x322E, .scripts = &.{ .Hani, } },
    .{ .code = 0x322F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3230, .scripts = &.{ .Hani, } },
    .{ .code = 0x3231, .scripts = &.{ .Hani, } },
    .{ .code = 0x3232, .scripts = &.{ .Hani, } },
    .{ .code = 0x3233, .scripts = &.{ .Hani, } },
    .{ .code = 0x3234, .scripts = &.{ .Hani, } },
    .{ .code = 0x3235, .scripts = &.{ .Hani, } },
    .{ .code = 0x3236, .scripts = &.{ .Hani, } },
    .{ .code = 0x3237, .scripts = &.{ .Hani, } },
    .{ .code = 0x3238, .scripts = &.{ .Hani, } },
    .{ .code = 0x3239, .scripts = &.{ .Hani, } },
    .{ .code = 0x323A, .scripts = &.{ .Hani, } },
    .{ .code = 0x323B, .scripts = &.{ .Hani, } },
    .{ .code = 0x323C, .scripts = &.{ .Hani, } },
    .{ .code = 0x323D, .scripts = &.{ .Hani, } },
    .{ .code = 0x323E, .scripts = &.{ .Hani, } },
    .{ .code = 0x323F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3240, .scripts = &.{ .Hani, } },
    .{ .code = 0x3241, .scripts = &.{ .Hani, } },
    .{ .code = 0x3242, .scripts = &.{ .Hani, } },
    .{ .code = 0x3243, .scripts = &.{ .Hani, } },
    .{ .code = 0x3244, .scripts = &.{ .Hani, } },
    .{ .code = 0x3245, .scripts = &.{ .Hani, } },
    .{ .code = 0x3246, .scripts = &.{ .Hani, } },
    .{ .code = 0x3247, .scripts = &.{ .Hani, } },
    .{ .code = 0x3280, .scripts = &.{ .Hani, } },
    .{ .code = 0x3281, .scripts = &.{ .Hani, } },
    .{ .code = 0x3282, .scripts = &.{ .Hani, } },
    .{ .code = 0x3283, .scripts = &.{ .Hani, } },
    .{ .code = 0x3284, .scripts = &.{ .Hani, } },
    .{ .code = 0x3285, .scripts = &.{ .Hani, } },
    .{ .code = 0x3286, .scripts = &.{ .Hani, } },
    .{ .code = 0x3287, .scripts = &.{ .Hani, } },
    .{ .code = 0x3288, .scripts = &.{ .Hani, } },
    .{ .code = 0x3289, .scripts = &.{ .Hani, } },
    .{ .code = 0x328A, .scripts = &.{ .Hani, } },
    .{ .code = 0x328B, .scripts = &.{ .Hani, } },
    .{ .code = 0x328C, .scripts = &.{ .Hani, } },
    .{ .code = 0x328D, .scripts = &.{ .Hani, } },
    .{ .code = 0x328E, .scripts = &.{ .Hani, } },
    .{ .code = 0x328F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3290, .scripts = &.{ .Hani, } },
    .{ .code = 0x3291, .scripts = &.{ .Hani, } },
    .{ .code = 0x3292, .scripts = &.{ .Hani, } },
    .{ .code = 0x3293, .scripts = &.{ .Hani, } },
    .{ .code = 0x3294, .scripts = &.{ .Hani, } },
    .{ .code = 0x3295, .scripts = &.{ .Hani, } },
    .{ .code = 0x3296, .scripts = &.{ .Hani, } },
    .{ .code = 0x3297, .scripts = &.{ .Hani, } },
    .{ .code = 0x3298, .scripts = &.{ .Hani, } },
    .{ .code = 0x3299, .scripts = &.{ .Hani, } },
    .{ .code = 0x329A, .scripts = &.{ .Hani, } },
    .{ .code = 0x329B, .scripts = &.{ .Hani, } },
    .{ .code = 0x329C, .scripts = &.{ .Hani, } },
    .{ .code = 0x329D, .scripts = &.{ .Hani, } },
    .{ .code = 0x329E, .scripts = &.{ .Hani, } },
    .{ .code = 0x329F, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A0, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A1, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A2, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A3, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A4, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A5, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A6, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A7, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A8, .scripts = &.{ .Hani, } },
    .{ .code = 0x32A9, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AA, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AB, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AC, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AD, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AE, .scripts = &.{ .Hani, } },
    .{ .code = 0x32AF, .scripts = &.{ .Hani, } },
    .{ .code = 0x32B0, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C0, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C1, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C2, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C3, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C4, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C5, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C6, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C7, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C8, .scripts = &.{ .Hani, } },
    .{ .code = 0x32C9, .scripts = &.{ .Hani, } },
    .{ .code = 0x32CA, .scripts = &.{ .Hani, } },
    .{ .code = 0x32CB, .scripts = &.{ .Hani, } },
    .{ .code = 0x32FF, .scripts = &.{ .Hani, } },
    .{ .code = 0x3358, .scripts = &.{ .Hani, } },
    .{ .code = 0x3359, .scripts = &.{ .Hani, } },
    .{ .code = 0x335A, .scripts = &.{ .Hani, } },
    .{ .code = 0x335B, .scripts = &.{ .Hani, } },
    .{ .code = 0x335C, .scripts = &.{ .Hani, } },
    .{ .code = 0x335D, .scripts = &.{ .Hani, } },
    .{ .code = 0x335E, .scripts = &.{ .Hani, } },
    .{ .code = 0x335F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3360, .scripts = &.{ .Hani, } },
    .{ .code = 0x3361, .scripts = &.{ .Hani, } },
    .{ .code = 0x3362, .scripts = &.{ .Hani, } },
    .{ .code = 0x3363, .scripts = &.{ .Hani, } },
    .{ .code = 0x3364, .scripts = &.{ .Hani, } },
    .{ .code = 0x3365, .scripts = &.{ .Hani, } },
    .{ .code = 0x3366, .scripts = &.{ .Hani, } },
    .{ .code = 0x3367, .scripts = &.{ .Hani, } },
    .{ .code = 0x3368, .scripts = &.{ .Hani, } },
    .{ .code = 0x3369, .scripts = &.{ .Hani, } },
    .{ .code = 0x336A, .scripts = &.{ .Hani, } },
    .{ .code = 0x336B, .scripts = &.{ .Hani, } },
    .{ .code = 0x336C, .scripts = &.{ .Hani, } },
    .{ .code = 0x336D, .scripts = &.{ .Hani, } },
    .{ .code = 0x336E, .scripts = &.{ .Hani, } },
    .{ .code = 0x336F, .scripts = &.{ .Hani, } },
    .{ .code = 0x3370, .scripts = &.{ .Hani, } },
    .{ .code = 0x337B, .scripts = &.{ .Hani, } },
    .{ .code = 0x337C, .scripts = &.{ .Hani, } },
    .{ .code = 0x337D, .scripts = &.{ .Hani, } },
    .{ .code = 0x337E, .scripts = &.{ .Hani, } },
    .{ .code = 0x337F, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E0, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E1, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E2, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E3, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E4, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E5, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E6, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E7, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E8, .scripts = &.{ .Hani, } },
    .{ .code = 0x33E9, .scripts = &.{ .Hani, } },
    .{ .code = 0x33EA, .scripts = &.{ .Hani, } },
    .{ .code = 0x33EB, .scripts = &.{ .Hani, } },
    .{ .code = 0x33EC, .scripts = &.{ .Hani, } },
    .{ .code = 0x33ED, .scripts = &.{ .Hani, } },
    .{ .code = 0x33EE, .scripts = &.{ .Hani, } },
    .{ .code = 0x33EF, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F0, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F1, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F2, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F3, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F4, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F5, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F6, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F7, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F8, .scripts = &.{ .Hani, } },
    .{ .code = 0x33F9, .scripts = &.{ .Hani, } },
    .{ .code = 0x33FA, .scripts = &.{ .Hani, } },
    .{ .code = 0x33FB, .scripts = &.{ .Hani, } },
    .{ .code = 0x33FC, .scripts = &.{ .Hani, } },
    .{ .code = 0x33FD, .scripts = &.{ .Hani, } },
    .{ .code = 0x33FE, .scripts = &.{ .Hani, } },
    .{ .code = 0xA66F, .scripts = &.{ .Cyrl, .Glag, } },
    .{ .code = 0xA700, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA701, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA702, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA703, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA704, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA705, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA706, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA707, .scripts = &.{ .Hani, .Latn, } },
    .{ .code = 0xA830, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Mlym, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA831, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Mlym, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA832, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Mlym, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA833, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA834, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA835, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Knda, .Kthi, .Mahj, .Modi, .Nand, .Shrd, .Sind, .Takr, .Tirh, .Tutg, } },
    .{ .code = 0xA836, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Kthi, .Mahj, .Modi, .Sind, .Takr, .Tirh, } },
    .{ .code = 0xA837, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Kthi, .Mahj, .Modi, .Sind, .Takr, .Tirh, } },
    .{ .code = 0xA838, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Kthi, .Mahj, .Modi, .Shrd, .Sind, .Takr, .Tirh, } },
    .{ .code = 0xA839, .scripts = &.{ .Deva, .Dogr, .Gujr, .Guru, .Khoj, .Kthi, .Mahj, .Modi, .Sind, .Takr, .Tirh, } },
    .{ .code = 0xA8F1, .scripts = &.{ .Beng, .Deva, .Tutg, } },
    .{ .code = 0xA8F3, .scripts = &.{ .Deva, .Taml, } },
    .{ .code = 0xA92E, .scripts = &.{ .Kali, .Latn, .Mymr, } },
    .{ .code = 0xA9CF, .scripts = &.{ .Bugi, .Java, } },
    .{ .code = 0xFD3E, .scripts = &.{ .Arab, .Nkoo, } },
    .{ .code = 0xFD3F, .scripts = &.{ .Arab, .Nkoo, } },
    .{ .code = 0xFDF2, .scripts = &.{ .Arab, .Thaa, } },
    .{ .code = 0xFDFD, .scripts = &.{ .Arab, .Thaa, } },
    .{ .code = 0xFE45, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0xFE46, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, } },
    .{ .code = 0xFF61, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0xFF62, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0xFF63, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0xFF64, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0xFF65, .scripts = &.{ .Bopo, .Hang, .Hani, .Hira, .Kana, .Yiii, } },
    .{ .code = 0xFF70, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0xFF9E, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0xFF9F, .scripts = &.{ .Hira, .Kana, } },
    .{ .code = 0x10100, .scripts = &.{ .Cpmn, .Cprt, .Linb, } },
    .{ .code = 0x10101, .scripts = &.{ .Cpmn, .Cprt, .Linb, } },
    .{ .code = 0x10102, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x10107, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10108, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10109, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010A, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010B, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010C, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010D, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010E, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1010F, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10110, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10111, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10112, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10113, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10114, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10115, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10116, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10117, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10118, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10119, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011A, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011B, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011C, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011D, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011E, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1011F, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10120, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10121, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10122, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10123, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10124, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10125, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10126, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10127, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10128, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10129, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012A, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012B, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012C, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012D, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012E, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x1012F, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10130, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10131, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10132, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10133, .scripts = &.{ .Cprt, .Lina, .Linb, } },
    .{ .code = 0x10137, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x10138, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x10139, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013A, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013B, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013C, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013D, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013E, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x1013F, .scripts = &.{ .Cprt, .Linb, } },
    .{ .code = 0x102E0, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E1, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E2, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E3, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E4, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E5, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E6, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E7, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E8, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102E9, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102EA, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102EB, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102EC, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102ED, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102EE, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102EF, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F0, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F1, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F2, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F3, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F4, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F5, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F6, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F7, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F8, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102F9, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102FA, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x102FB, .scripts = &.{ .Arab, .Copt, } },
    .{ .code = 0x10AF2, .scripts = &.{ .Mani, .Ougr, } },
    .{ .code = 0x11301, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x11303, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x1133B, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x1133C, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x11FD0, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x11FD1, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x11FD3, .scripts = &.{ .Gran, .Taml, } },
    .{ .code = 0x1BCA0, .scripts = &.{ .Dupl, } },
    .{ .code = 0x1BCA1, .scripts = &.{ .Dupl, } },
    .{ .code = 0x1BCA2, .scripts = &.{ .Dupl, } },
    .{ .code = 0x1BCA3, .scripts = &.{ .Dupl, } },
    .{ .code = 0x1D360, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D361, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D362, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D363, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D364, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D365, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D366, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D367, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D368, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D369, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36A, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36B, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36C, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36D, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36E, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D36F, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D370, .scripts = &.{ .Hani, } },
    .{ .code = 0x1D371, .scripts = &.{ .Hani, } },
    .{ .code = 0x1F250, .scripts = &.{ .Hani, } },
    .{ .code = 0x1F251, .scripts = &.{ .Hani, } },
};
